/* eslint-disable react/no-unknown-property, no-unused-vars */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/scene/EscenadePrueba1.gltf -o src/components/Scene.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"/../src/assets/scene/EscenadePrueba1.gltf"
	);
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group
					name="Plane009"
					position={[125.693, 292.734, 0.028]}
					scale={0.508}
				/>
				<mesh
					name="planetaFinalIsla1"
					geometry={nodes.planetaFinalIsla1.geometry}
					material={materials.planetaTexIsla1}
					position={[-308.06, -0.65, 0.898]}
					rotation={[-0.259, 0.146, 0.017]}
					scale={[0.015, 0.032, 0.051]}
				/>
				<group
					name="waterFinalIsla1"
					position={[-308.06, -0.65, 0.898]}
					rotation={[-0.259, 0.146, 0.017]}
					scale={[0.015, 0.032, 0.051]}
				>
					<mesh
						name="waterFinalIsla1_1"
						geometry={nodes.waterFinalIsla1_1.geometry}
						material={materials.waterTexIsla1}
					/>
					<mesh
						name="waterFinalIsla1_2"
						geometry={nodes.waterFinalIsla1_2.geometry}
						material={materials.outlineTexIsla1}
					/>
				</group>
				<group
					name="koiFinalIsla1"
					position={[-308.06, -0.65, 0.898]}
					rotation={[-0.259, 0.146, 0.017]}
					scale={[0.015, 0.032, 0.051]}
				>
					<mesh
						name="koiFinalIsla1_1"
						geometry={nodes.koiFinalIsla1_1.geometry}
						material={materials.koiTexIsla1}
					/>
					<mesh
						name="koiFinalIsla1_2"
						geometry={nodes.koiFinalIsla1_2.geometry}
						material={materials.outlineTexIsla1}
					/>
				</group>
				<group
					name="piedrasFinalIsla1"
					position={[-308.06, -0.65, 0.898]}
					rotation={[-0.259, 0.146, 0.017]}
					scale={[0.015, 0.032, 0.051]}
				>
					<mesh
						name="piedrasFinalIsla1_1"
						geometry={nodes.piedrasFinalIsla1_1.geometry}
						material={materials.baseTexIsla1}
					/>
					<mesh
						name="piedrasFinalIsla1_2"
						geometry={nodes.piedrasFinalIsla1_2.geometry}
						material={materials.outlineTexIsla1}
					/>
				</group>
				<mesh
					name="baseFinalIsla1"
					geometry={nodes.baseFinalIsla1.geometry}
					material={materials.baseTexIsla1}
					position={[-308.06, -0.65, 0.898]}
					rotation={[-0.259, 0.146, 0.017]}
					scale={[0.015, 0.032, 0.051]}
				/>
				<group
					name="plantasFinalIsla1"
					position={[-308.06, -0.65, 0.898]}
					rotation={[-0.259, 0.146, 0.017]}
					scale={[0.015, 0.032, 0.051]}
				>
					<mesh
						name="plantasFinalIsla1001"
						geometry={nodes.plantasFinalIsla1001.geometry}
						material={materials.foliageTexIsla1}
					/>
					<mesh
						name="plantasFinalIsla1001_1"
						geometry={nodes.plantasFinalIsla1001_1.geometry}
						material={materials.baseTexIsla1}
					/>
					<mesh
						name="plantasFinalIsla1001_2"
						geometry={nodes.plantasFinalIsla1001_2.geometry}
						material={materials.outlineTexIsla1}
					/>
				</group>
				<mesh
					name="accesoriosIsla2"
					geometry={nodes.accesoriosIsla2.geometry}
					material={materials.characterIsla2}
					position={[0.126, 0.012, -0.06]}
				/>
				<group
					name="hairIsla2"
					position={[-214.526, 162.954, -0.31]}
					scale={1.48}
				>
					<mesh
						name="RetopoFlow002"
						geometry={nodes.RetopoFlow002.geometry}
						material={materials.characterIsla2}
					/>
					<mesh
						name="RetopoFlow002_1"
						geometry={nodes.RetopoFlow002_1.geometry}
						material={materials.outlineIsla2}
					/>
				</group>
				<group
					name="clothesIsla2"
					position={[-215.958, 163.622, -0.038]}
					scale={1.48}
				>
					<mesh
						name="RetopoFlow"
						geometry={nodes.RetopoFlow.geometry}
						material={materials.characterIsla2}
					/>
					<mesh
						name="RetopoFlow_1"
						geometry={nodes.RetopoFlow_1.geometry}
						material={materials.outlineIsla2}
					/>
				</group>
				<group
					name="bambooIsla2"
					position={[-212.066, 162.924, 2.349]}
					rotation={[Math.PI, -0.264, Math.PI]}
					scale={1.48}
				>
					<mesh
						name="Plane004_1"
						geometry={nodes.Plane004_1.geometry}
						material={materials.foliageIsla2}
					/>
					<mesh
						name="Plane004_2"
						geometry={nodes.Plane004_2.geometry}
						material={materials.outlineIsla2}
					/>
				</group>
				<group
					name="baseIsla2"
					position={[-215.051, 161.801, 1.192]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={1.48}
				>
					<mesh
						name="Plane047_1"
						geometry={nodes.Plane047_1.geometry}
						material={materials.textureIsla2}
					/>
					<mesh
						name="Plane047_2"
						geometry={nodes.Plane047_2.geometry}
						material={materials.outlineIsla2}
					/>
				</group>
				<mesh
					name="foliageIsla2"
					geometry={nodes.foliageIsla2.geometry}
					material={materials.foliageIsla2}
					position={[-212.066, 162.924, 2.349]}
					rotation={[Math.PI, -0.264, Math.PI]}
					scale={1.48}
				/>
				<mesh
					name="humoIsla2"
					geometry={nodes.humoIsla2.geometry}
					material={materials.foliageIsla2}
					position={[-217.203, 164.15, -0.217]}
					rotation={[2.958, 0.054, -3.012]}
					scale={1.48}
				/>
				<group
					name="maderaIsla2"
					position={[-213.763, 164.326, -1.362]}
					rotation={[Math.PI, -0.712, Math.PI]}
					scale={1.48}
				>
					<mesh
						name="Plane008_1"
						geometry={nodes.Plane008_1.geometry}
						material={materials.textureIsla2}
					/>
					<mesh
						name="Plane008_2"
						geometry={nodes.Plane008_2.geometry}
						material={materials.outlineIsla2}
					/>
				</group>
				<group
					name="paredIsla2"
					position={[-213.763, 164.326, -1.362]}
					rotation={[Math.PI, -0.712, Math.PI]}
					scale={1.48}
				>
					<mesh
						name="Plane009_1"
						geometry={nodes.Plane009_1.geometry}
						material={materials.textureIsla2}
					/>
					<mesh
						name="Plane009_2"
						geometry={nodes.Plane009_2.geometry}
						material={materials.outlineIsla2}
					/>
				</group>
				<group
					name="rocksIsla2"
					position={[-212.718, 163.188, 3.563]}
					rotation={[0.008, -0.253, -0.014]}
					scale={1.48}
				>
					<mesh
						name="Sphere"
						geometry={nodes.Sphere.geometry}
						material={materials.textureIsla2}
					/>
					<mesh
						name="Sphere_1"
						geometry={nodes.Sphere_1.geometry}
						material={materials.outlineIsla2}
					/>
				</group>
				<mesh
					name="planetIsla2"
					geometry={nodes.planetIsla2.geometry}
					material={materials.planetIsla2}
					position={[-214.712, 162.937, -0.225]}
					scale={19.809}
				/>
				<group
					name="teaIsla2"
					position={[-215.939, 164.197, -0.012]}
					scale={1.48}
				>
					<mesh
						name="Circle002_1"
						geometry={nodes.Circle002_1.geometry}
						material={materials.foliageIsla2}
					/>
					<mesh
						name="Circle002_2"
						geometry={nodes.Circle002_2.geometry}
						material={materials.outlineIsla2}
					/>
				</group>
				<group
					name="grassIsla3"
					position={[0, -1.263, 0.858]}
					rotation={[Math.PI, 0, Math.PI]}
				>
					<mesh
						name="Circle_1"
						geometry={nodes.Circle_1.geometry}
						material={materials.grass}
					/>
					<mesh
						name="Circle_2"
						geometry={nodes.Circle_2.geometry}
						material={materials.outlineIsla3}
					/>
				</group>
				<group
					name="treeIsla3"
					position={[-55.357, 247.7, -0.791]}
					scale={0.94}
				>
					<mesh
						name="Plane001_1"
						geometry={nodes.Plane001_1.geometry}
						material={materials.treeIsla3}
					/>
					<mesh
						name="Plane001_2"
						geometry={nodes.Plane001_2.geometry}
						material={materials.outlineIsla3}
					/>
				</group>
				<group
					name="leavesIsla3"
					position={[-53.03, 251.361, -0.319]}
					rotation={[0.489, 0, 0]}
					scale={0.94}
				>
					<mesh
						name="Plane016_1"
						geometry={nodes.Plane016_1.geometry}
						material={materials.hojasIsla3}
					/>
					<mesh
						name="Plane016_2"
						geometry={nodes.Plane016_2.geometry}
						material={materials.grass}
					/>
				</group>
				<mesh
					name="waterIsla3"
					geometry={nodes.waterIsla3.geometry}
					material={materials.water}
					position={[-54.762, 246.318, 0.831]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.94}
				/>
				<mesh
					name="lightsIsla3"
					geometry={nodes.lightsIsla3.geometry}
					material={materials.Light}
					position={[-54.762, 248.736, 0.826]}
					scale={0.94}
				/>
				<group
					name="clothesIsla3"
					position={[-54.762, 247.828, 0.594]}
					scale={0.94}
				>
					<mesh
						name="Circle003_1"
						geometry={nodes.Circle003_1.geometry}
						material={materials.clothesIsla3}
					/>
					<mesh
						name="Circle003_2"
						geometry={nodes.Circle003_2.geometry}
						material={materials.outlineIsla3}
					/>
				</group>
				<group
					name="cuerpoIsla3"
					position={[-54.762, 247.835, 0.594]}
					scale={0.94}
				>
					<mesh
						name="Body_(merged)baked006"
						geometry={nodes["Body_(merged)baked006"].geometry}
						material={materials.character}
					/>
					<mesh
						name="Body_(merged)baked006_1"
						geometry={nodes["Body_(merged)baked006_1"].geometry}
						material={materials.outlineIsla3}
					/>
				</group>
				<mesh
					name="accesoriosIsla3"
					geometry={nodes.accesoriosIsla3.geometry}
					material={materials.character}
					position={[-54.762, 247.835, 0.594]}
					scale={1.303}
				/>
				<group
					name="hairIsla3"
					position={[-54.762, 247.835, 0.594]}
					scale={0.94}
				>
					<mesh
						name="RetopoFlow007"
						geometry={nodes.RetopoFlow007.geometry}
						material={materials.character}
					/>
					<mesh
						name="RetopoFlow007_1"
						geometry={nodes.RetopoFlow007_1.geometry}
						material={materials.outline}
					/>
				</group>
				<group
					name="rocksIsla3"
					position={[-55.505, 247.673, 0.326]}
					rotation={[-0.17, -0.655, -0.241]}
					scale={0.94}
				>
					<mesh
						name="Cube002"
						geometry={nodes.Cube002.geometry}
						material={materials.rocks}
					/>
					<mesh
						name="Cube002_1"
						geometry={nodes.Cube002_1.geometry}
						material={materials.outlineIsla3}
					/>
				</group>
				<group
					name="baseIsla3"
					position={[-54.762, 246.344, 0.873]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.94}
				>
					<mesh
						name="Circle004_1"
						geometry={nodes.Circle004_1.geometry}
						material={materials["Material.001"]}
					/>
					<mesh
						name="Circle004_2"
						geometry={nodes.Circle004_2.geometry}
						material={materials.outline}
					/>
				</group>
				<group
					name="mushroomIsla3"
					position={[-55.532, 247.46, -0.364]}
					rotation={[-2.943, -0.745, -3.014]}
					scale={0.94}
				>
					<mesh
						name="Circle005_1"
						geometry={nodes.Circle005_1.geometry}
						material={materials.treeIsla3}
					/>
					<mesh
						name="Circle005_2"
						geometry={nodes.Circle005_2.geometry}
						material={materials.outline}
					/>
				</group>
				<mesh
					name="planetaIsla3"
					geometry={nodes.planetaIsla3.geometry}
					material={materials.planetIsla3}
					position={[-55.004, 248.851, 0.726]}
					scale={20.556}
				/>
				<group name="Circle003" position={[-3.073, 9.072, -3.621]}>
					<mesh
						name="Circle006_1"
						geometry={nodes.Circle006_1.geometry}
						material={materials.farolIsla4Tex}
					/>
					<mesh
						name="Circle006_2"
						geometry={nodes.Circle006_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<mesh
					name="Cylinder"
					geometry={nodes.Cylinder.geometry}
					material={materials.lightIsla4}
					position={[123.821, 299.567, -1.621]}
					rotation={[0, 0.693, -1.598]}
					scale={0.508}
				/>
				<mesh
					name="Cylinder001"
					geometry={nodes.Cylinder001.geometry}
					material={materials.lightIsla4}
					position={[124.367, 299.567, -1.941]}
					rotation={[Math.PI, -0.617, 1.544]}
					scale={0.508}
				/>
				<group
					name="Circle015"
					position={[121.037, 292.654, -1.728]}
					rotation={[0, -1.064, 0]}
					scale={0.508}
				>
					<mesh
						name="Circle016"
						geometry={nodes.Circle016.geometry}
						material={materials.coral}
					/>
					<mesh
						name="Circle016_1"
						geometry={nodes.Circle016_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Circle021"
					position={[123.02, 292.979, -3.665]}
					rotation={[-0.654, 1.192, -0.577]}
					scale={0.508}
				>
					<mesh
						name="Circle022"
						geometry={nodes.Circle022.geometry}
						material={materials.coral2Isla4tex}
					/>
					<mesh
						name="Circle022_1"
						geometry={nodes.Circle022_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Circle036"
					position={[129.654, 293.198, 2.526]}
					rotation={[0.557, 0.274, -0.675]}
					scale={0.508}
				>
					<mesh
						name="Circle037"
						geometry={nodes.Circle037.geometry}
						material={materials.coral3Isla4Tex}
					/>
					<mesh
						name="Circle037_1"
						geometry={nodes.Circle037_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Circle028"
					position={[122.745, 292.986, 3.149]}
					rotation={[0.908, -0.31, 0.482]}
					scale={0.508}
				>
					<mesh
						name="Circle047"
						geometry={nodes.Circle047.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Circle047_1"
						geometry={nodes.Circle047_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<mesh
					name="Circle068"
					geometry={nodes.Circle068.geometry}
					material={materials.fishIsla4Tex}
					position={[121.844, 293.097, -4.298]}
					rotation={[-0.34, 0.796, -0.582]}
					scale={[0.073, 0.039, 0.073]}
				/>
				<mesh
					name="Circle077"
					geometry={nodes.Circle077.geometry}
					material={materials.coral}
					position={[125.53, 293.028, -3.262]}
					rotation={[0, 1.568, 0]}
					scale={0.312}
				/>
				<group name="hair001" position={[127.34, 297.463, 1.123]} scale={0.508}>
					<mesh
						name="RetopoFlow001"
						geometry={nodes.RetopoFlow001.geometry}
						material={materials.characterIsla4Tex}
					/>
					<mesh
						name="RetopoFlow001_1"
						geometry={nodes.RetopoFlow001_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<mesh
					name="acceorios001"
					geometry={nodes.acceorios001.geometry}
					material={materials.characterIsla4Tex}
					position={[127.34, 295.291, 1.138]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.508}
				/>
				<group
					name="fullBody001"
					position={[127.34, 295.292, 1.136]}
					scale={0.508}
				>
					<mesh
						name="Face_(merged)(Clone)baked014"
						geometry={nodes["Face_(merged)(Clone)baked014"].geometry}
						material={materials.characterIsla4Tex}
					/>
					<mesh
						name="Face_(merged)(Clone)baked014_1"
						geometry={nodes["Face_(merged)(Clone)baked014_1"].geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="camista001"
					position={[127.34, 295.292, 1.136]}
					scale={0.508}
				>
					<mesh
						name="Face_(merged)(Clone)baked015"
						geometry={nodes["Face_(merged)(Clone)baked015"].geometry}
						material={materials.camisetaIsla4Tex}
					/>
					<mesh
						name="Face_(merged)(Clone)baked015_1"
						geometry={nodes["Face_(merged)(Clone)baked015_1"].geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="pantalon001"
					position={[127.34, 295.292, 1.136]}
					scale={0.508}
				>
					<mesh
						name="Face_(merged)(Clone)baked016"
						geometry={nodes["Face_(merged)(Clone)baked016"].geometry}
						material={materials.pantalonIsla4Tex}
					/>
					<mesh
						name="Face_(merged)(Clone)baked016_1"
						geometry={nodes["Face_(merged)(Clone)baked016_1"].geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="capaIsla4001"
					position={[127.34, 295.292, 1.136]}
					scale={0.508}
				>
					<mesh
						name="Face_(merged)(Clone)baked017"
						geometry={nodes["Face_(merged)(Clone)baked017"].geometry}
						material={materials.capaIsla4Tex}
					/>
					<mesh
						name="Face_(merged)(Clone)baked017_1"
						geometry={nodes["Face_(merged)(Clone)baked017_1"].geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Sombrero001"
					position={[127.34, 295.292, 1.136]}
					scale={0.508}
				>
					<mesh
						name="Circle007_1"
						geometry={nodes.Circle007_1.geometry}
						material={materials.sombreroIsla4Tex}
					/>
					<mesh
						name="Circle007_2"
						geometry={nodes.Circle007_2.geometry}
						material={materials.cintasIsla4}
					/>
					<mesh
						name="Circle007_3"
						geometry={nodes.Circle007_3.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group name="Cube" position={[126.34, 294.345, 0.456]} scale={0.508}>
					<mesh
						name="Cube001_1"
						geometry={nodes.Cube001_1.geometry}
						material={materials["baseIsla4.001"]}
					/>
					<mesh
						name="Cube001_2"
						geometry={nodes.Cube001_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane002"
					position={[126.34, 294.345, 0.456]}
					scale={0.508}
				>
					<mesh
						name="Plane003_1"
						geometry={nodes.Plane003_1.geometry}
						material={materials.waterIsla4}
					/>
					<mesh
						name="Plane003_2"
						geometry={nodes.Plane003_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<mesh
					name="planetaIsla4"
					geometry={nodes.planetaIsla4.geometry}
					material={materials.fondo}
					position={[126.34, 294.345, 0.456]}
					rotation={[0, -1.205, 0]}
					scale={0.6}
				/>
				<mesh
					name="Plane003"
					geometry={nodes.Plane003.geometry}
					material={materials.cafe}
					position={[126.34, 294.345, 0.456]}
					scale={0.508}
				/>
				<group
					name="Cube001"
					position={[126.156, 294.465, 0.246]}
					scale={[0.648, 0.526, 0.648]}
				>
					<mesh
						name="Cube035"
						geometry={nodes.Cube035.geometry}
						material={materials["baseIsla4.001"]}
					/>
					<mesh
						name="Cube035_1"
						geometry={nodes.Cube035_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<mesh
					name="Circle"
					geometry={nodes.Circle.geometry}
					material={materials.cafe}
					position={[127.219, 293.425, 1.196]}
					rotation={[0, -1.419, 0]}
					scale={0.648}
				/>
				<mesh
					name="Plane"
					geometry={nodes.Plane.geometry}
					material={materials.baseIsla4}
					position={[125.693, 292.595, 0.028]}
					scale={[0.508, 0.646, 0.508]}
				/>
				<group
					name="weed1f"
					position={[126.429, 294.105, -0.961]}
					rotation={[-1.142, -0.435, -1.458]}
					scale={0.158}
				>
					<mesh
						name="Plane025_1"
						geometry={nodes.Plane025_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane025_2"
						geometry={nodes.Plane025_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed1f001"
					position={[123.233, 294.171, 0.795]}
					rotation={[-0.282, -0.609, -0.462]}
					scale={0.101}
				>
					<mesh
						name="Plane027_1"
						geometry={nodes.Plane027_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane027_2"
						geometry={nodes.Plane027_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed2001"
					position={[124.707, 294.034, 0.766]}
					rotation={[-0.437, -0.605, -0.821]}
					scale={0.077}
				>
					<mesh
						name="Plane040_1"
						geometry={nodes.Plane040_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane040_2"
						geometry={nodes.Plane040_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed2002"
					position={[128.53, 294.101, -0.775]}
					rotation={[-1.634, -1.123, -2.061]}
					scale={0.077}
				>
					<mesh
						name="Plane041_1"
						geometry={nodes.Plane041_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane041_2"
						geometry={nodes.Plane041_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed2003"
					position={[129.128, 294.127, -1.428]}
					rotation={[-0.293, 0.275, -0.033]}
					scale={0.11}
				>
					<mesh
						name="Plane042_1"
						geometry={nodes.Plane042_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane042_2"
						geometry={nodes.Plane042_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed2004"
					position={[122.07, 294.164, -3.192]}
					rotation={[-0.315, 0.163, 0.303]}
					scale={0.079}
				>
					<mesh
						name="Plane043"
						geometry={nodes.Plane043.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane043_1"
						geometry={nodes.Plane043_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed1f002"
					position={[129.015, 294.177, -0.232]}
					rotation={[-1.427, -0.631, -1.457]}
					scale={0.07}
				>
					<mesh
						name="Plane044_1"
						geometry={nodes.Plane044_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane044_2"
						geometry={nodes.Plane044_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed4001"
					position={[124.214, 294.304, 0.493]}
					scale={0.186}
				>
					<mesh
						name="Plane051_1"
						geometry={nodes.Plane051_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane051_2"
						geometry={nodes.Plane051_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed4002"
					position={[126.719, 294.304, -1.611]}
					scale={0.186}
				>
					<mesh
						name="Plane052"
						geometry={nodes.Plane052.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane052_1"
						geometry={nodes.Plane052_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed4003"
					position={[128.052, 294.304, -1.392]}
					rotation={[0, -0.768, 0]}
					scale={0.186}
				>
					<mesh
						name="Plane053"
						geometry={nodes.Plane053.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane053_1"
						geometry={nodes.Plane053_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed4004"
					position={[128.921, 294.304, -2.546]}
					rotation={[0, -1.528, 0]}
					scale={0.186}
				>
					<mesh
						name="Plane054"
						geometry={nodes.Plane054.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane054_1"
						geometry={nodes.Plane054_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed3001"
					position={[122.324, 294.333, -0.759]}
					rotation={[0, -1.266, 0]}
					scale={0.222}
				>
					<mesh
						name="Plane006_1"
						geometry={nodes.Plane006_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane006_2"
						geometry={nodes.Plane006_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed3002"
					position={[125.118, 294.289, 0.234]}
					rotation={[-0.082, 0.611, -0.052]}
					scale={0.222}
				>
					<mesh
						name="Plane056_1"
						geometry={nodes.Plane056_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane056_2"
						geometry={nodes.Plane056_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed3003"
					position={[127.214, 294.081, -1.161]}
					rotation={[-0.075, 0.121, 0.02]}
					scale={0.222}
				>
					<mesh
						name="Plane057_1"
						geometry={nodes.Plane057_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane057_2"
						geometry={nodes.Plane057_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed3004"
					position={[125.844, 294.321, -1.202]}
					rotation={[-0.174, 1.124, 0.168]}
					scale={0.222}
				>
					<mesh
						name="Plane058"
						geometry={nodes.Plane058.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane058_1"
						geometry={nodes.Plane058_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed1f003"
					position={[126.425, 293.681, 1.389]}
					rotation={[-0.693, -1.046, -0.794]}
					scale={0.1}
				>
					<mesh
						name="Plane059_1"
						geometry={nodes.Plane059_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane059_2"
						geometry={nodes.Plane059_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed3005"
					position={[127.27, 293.752, 1.986]}
					rotation={[-0.075, 0.121, 0.02]}
					scale={0.283}
				>
					<mesh
						name="Plane060_1"
						geometry={nodes.Plane060_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane060_2"
						geometry={nodes.Plane060_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed3006"
					position={[126.972, 293.776, 0.567]}
					rotation={[-0.081, 0.377, 0.04]}
					scale={0.283}
				>
					<mesh
						name="Plane061_1"
						geometry={nodes.Plane061_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane061_2"
						geometry={nodes.Plane061_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="weed4005"
					position={[127.986, 293.707, 1.056]}
					rotation={[0, -1.423, 0]}
					scale={0.238}
				>
					<mesh
						name="Plane062_1"
						geometry={nodes.Plane062_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane062_2"
						geometry={nodes.Plane062_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane030"
					position={[124.035, 293.998, 1.034]}
					rotation={[-0.237, -1.115, -0.214]}
					scale={0.264}
				>
					<mesh
						name="Plane082"
						geometry={nodes.Plane082.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane082_1"
						geometry={nodes.Plane082_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane031"
					position={[127.535, 294.299, -1.469]}
					rotation={[-0.237, -1.115, -0.214]}
					scale={[0.156, 0.157, 0.156]}
				>
					<mesh
						name="Plane083"
						geometry={nodes.Plane083.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane083_1"
						geometry={nodes.Plane083_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane032"
					position={[125.533, 294.299, -0.246]}
					rotation={[-0.237, -1.115, -0.214]}
					scale={[0.156, 0.157, 0.156]}
				>
					<mesh
						name="Plane084"
						geometry={nodes.Plane084.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane084_1"
						geometry={nodes.Plane084_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane033"
					position={[129.24, 294.153, -2.108]}
					rotation={[-0.511, -1.042, -0.603]}
					scale={[0.156, 0.157, 0.156]}
				>
					<mesh
						name="Plane085"
						geometry={nodes.Plane085.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane085_1"
						geometry={nodes.Plane085_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane034"
					position={[122.242, 293.981, 0.273]}
					rotation={[-0.237, -1.115, -0.214]}
					scale={[0.156, 0.222, 0.157]}
				>
					<mesh
						name="Plane086"
						geometry={nodes.Plane086.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane086_1"
						geometry={nodes.Plane086_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane044"
					position={[125.501, 294.102, 0.264]}
					rotation={[-0.388, -0.798, -0.301]}
					scale={0.231}
				>
					<mesh
						name="Plane103"
						geometry={nodes.Plane103.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane103_1"
						geometry={nodes.Plane103_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane045"
					position={[127.266, 294.102, -1.027]}
					rotation={[-2.15, -1.25, -2.19]}
					scale={0.231}
				>
					<mesh
						name="Plane104"
						geometry={nodes.Plane104.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane104_1"
						geometry={nodes.Plane104_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane046"
					position={[129.135, 294.249, -3.084]}
					rotation={[-2.15, -1.25, -2.19]}
					scale={0.166}
				>
					<mesh
						name="Plane105"
						geometry={nodes.Plane105.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane105_1"
						geometry={nodes.Plane105_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane047"
					position={[121.989, 294.249, -1.857]}
					rotation={[-2.15, -1.25, -2.19]}
					scale={0.166}
				>
					<mesh
						name="Plane106"
						geometry={nodes.Plane106.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane106_1"
						geometry={nodes.Plane106_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane048"
					position={[128.001, 293.84, 1.754]}
					rotation={[-1.976, -1.192, -2.059]}
					scale={0.295}
				>
					<mesh
						name="Plane107"
						geometry={nodes.Plane107.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane107_1"
						geometry={nodes.Plane107_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane049"
					position={[127.789, 294.127, -1.073]}
					rotation={[0.5, 0.124, 0.282]}
					scale={0.176}
				>
					<mesh
						name="Plane108"
						geometry={nodes.Plane108.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane108_1"
						geometry={nodes.Plane108_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane051"
					position={[122.804, 294.079, 0.585]}
					rotation={[-0.088, 1.099, 0.646]}
					scale={0.148}
				>
					<mesh
						name="Plane109"
						geometry={nodes.Plane109.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane109_1"
						geometry={nodes.Plane109_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane055"
					position={[122.344, 294.095, -0.183]}
					rotation={[0.223, 0.141, 0.484]}
					scale={0.118}
				>
					<mesh
						name="Plane113"
						geometry={nodes.Plane113.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane113_1"
						geometry={nodes.Plane113_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane056"
					position={[126.824, 294.072, -1.277]}
					rotation={[0.644, -0.749, 0.055]}
					scale={0.153}
				>
					<mesh
						name="Plane114"
						geometry={nodes.Plane114.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane114_1"
						geometry={nodes.Plane114_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane057"
					position={[129.302, 293.957, -2.603]}
					rotation={[-0.263, -0.012, -1.23]}
					scale={0.171}
				>
					<mesh
						name="Plane115"
						geometry={nodes.Plane115.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane115_1"
						geometry={nodes.Plane115_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane059"
					position={[126.445, 293.611, 0.887]}
					rotation={[2.868, 0.051, 2.519]}
					scale={0.244}
				>
					<mesh
						name="Plane117"
						geometry={nodes.Plane117.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane117_1"
						geometry={nodes.Plane117_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane060"
					position={[125.855, 293.924, -0.326]}
					rotation={[-0.218, -0.643, -1.096]}
					scale={0.171}
				>
					<mesh
						name="Plane118"
						geometry={nodes.Plane118.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane118_1"
						geometry={nodes.Plane118_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane061"
					position={[121.89, 293.98, -2.69]}
					rotation={[-0.354, 0.185, 1.409]}
					scale={0.169}
				>
					<mesh
						name="Plane119"
						geometry={nodes.Plane119.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane119_1"
						geometry={nodes.Plane119_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane062"
					position={[126.595, 293.499, 1.926]}
					rotation={[0.566, 0.098, 0.571]}
					scale={0.184}
				>
					<mesh
						name="Plane120"
						geometry={nodes.Plane120.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane120_1"
						geometry={nodes.Plane120_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane065"
					position={[128.077, 293.874, -0.689]}
					rotation={[0.872, -0.417, 0.366]}
					scale={0.07}
				>
					<mesh
						name="Plane007_1"
						geometry={nodes.Plane007_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane007_2"
						geometry={nodes.Plane007_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane066"
					position={[122.282, 294.103, -1.278]}
					rotation={[-2.231, 0.983, 2.193]}
					scale={0.508}
				>
					<mesh
						name="Plane010_1"
						geometry={nodes.Plane010_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane010_2"
						geometry={nodes.Plane010_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane068"
					position={[124.706, 293.486, 0.847]}
					rotation={[-2.465, -0.149, -2.788]}
					scale={0.508}
				>
					<mesh
						name="Plane018_1"
						geometry={nodes.Plane018_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane018_2"
						geometry={nodes.Plane018_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane070"
					position={[126.503, 293.67, -0.675]}
					rotation={[-1.905, -0.682, -2.971]}
					scale={0.508}
				>
					<mesh
						name="Plane020_1"
						geometry={nodes.Plane020_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane020_2"
						geometry={nodes.Plane020_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish1"
					position={[128.79, 293.842, 0.472]}
					rotation={[0.08, 0.188, -0.067]}
					scale={0.508}
				>
					<mesh
						name="Plane021_1"
						geometry={nodes.Plane021_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane021_2"
						geometry={nodes.Plane021_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish2"
					position={[122.627, 293.811, 1.85]}
					rotation={[0.534, 0.671, -0.446]}
					scale={0.421}
				>
					<mesh
						name="Plane022_1"
						geometry={nodes.Plane022_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane022_2"
						geometry={nodes.Plane022_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish3"
					position={[125.131, 293.93, 2.438]}
					rotation={[3.133, -1.221, 3.134]}
					scale={0.508}
				>
					<mesh
						name="Plane036_1"
						geometry={nodes.Plane036_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane036_2"
						geometry={nodes.Plane036_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish3001"
					position={[125.597, 294.311, 2.298]}
					rotation={[3.133, -1.221, 3.134]}
					scale={0.508}
				>
					<mesh
						name="Plane038_1"
						geometry={nodes.Plane038_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane038_2"
						geometry={nodes.Plane038_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish3002"
					position={[125.58, 293.705, 2.678]}
					rotation={[3.133, -1.221, 3.134]}
					scale={0.508}
				>
					<mesh
						name="Plane045_1"
						geometry={nodes.Plane045_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane045_2"
						geometry={nodes.Plane045_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish3003"
					position={[125.823, 294.023, 3.086]}
					rotation={[3.133, -1.221, 3.134]}
					scale={0.508}
				>
					<mesh
						name="Plane046_1"
						geometry={nodes.Plane046_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane046_2"
						geometry={nodes.Plane046_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish2001"
					position={[123.325, 293.938, 2.022]}
					rotation={[0.689, 0.901, -0.504]}
					scale={0.421}
				>
					<mesh
						name="Plane011_1"
						geometry={nodes.Plane011_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane011_2"
						geometry={nodes.Plane011_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish2002"
					position={[122.854, 294.374, 1.473]}
					rotation={[0.424, 0.455, -0.435]}
					scale={0.421}
				>
					<mesh
						name="Plane049_1"
						geometry={nodes.Plane049_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane049_2"
						geometry={nodes.Plane049_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish2003"
					position={[122.356, 294.079, 0.888]}
					rotation={[0.387, 0.377, -0.437]}
					scale={0.421}
				>
					<mesh
						name="Plane071_1"
						geometry={nodes.Plane071_1.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane071_2"
						geometry={nodes.Plane071_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish1001"
					position={[128.968, 293.401, 1.354]}
					rotation={[-0.049, -0.133, 0.038]}
					scale={0.508}
				>
					<mesh
						name="Plane073"
						geometry={nodes.Plane073.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane073_1"
						geometry={nodes.Plane073_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish1002"
					position={[128.65, 294.035, 1.793]}
					rotation={[-0.106, -0.308, 0.079]}
					scale={0.508}
				>
					<mesh
						name="Plane074"
						geometry={nodes.Plane074.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane074_1"
						geometry={nodes.Plane074_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Fish3004"
					position={[126.331, 293.684, 2.718]}
					rotation={[3.133, -1.221, 3.134]}
					scale={0.508}
				>
					<mesh
						name="Plane075"
						geometry={nodes.Plane075.geometry}
						material={materials.fishIsla4Tex}
					/>
					<mesh
						name="Plane075_1"
						geometry={nodes.Plane075_1.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Plane071"
					position={[127.466, 293.001, 3.747]}
					rotation={[-1.905, -0.682, -2.971]}
					scale={0.508}
				>
					<mesh
						name="Plane023_1"
						geometry={nodes.Plane023_1.geometry}
						material={materials.weeds}
					/>
					<mesh
						name="Plane023_2"
						geometry={nodes.Plane023_2.geometry}
						material={materials["outline.001"]}
					/>
				</group>
				<group
					name="Icosphere"
					position={[-0.008, 5.163, 2.009]}
					rotation={[0, 1.242, 0]}
					scale={[1.44, 0.995, 1.44]}
				>
					<mesh
						name="Icosphere_1"
						geometry={nodes.Icosphere_1.geometry}
						material={materials.crystalIsla5Mat}
					/>
					<mesh
						name="Icosphere_2"
						geometry={nodes.Icosphere_2.geometry}
						material={materials.outlinewhiteIsla5}
					/>
					<mesh
						name="Icosphere_3"
						geometry={nodes.Icosphere_3.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Circle001"
					position={[272.705, 269.904, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Circle009"
						geometry={nodes.Circle009.geometry}
						material={materials.grassIsla5Tex}
					/>
					<mesh
						name="Circle009_1"
						geometry={nodes.Circle009_1.geometry}
						material={materials.stalactitesIsla5Mat}
					/>
					<mesh
						name="Circle009_2"
						geometry={nodes.Circle009_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Circle002"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Circle010"
						geometry={nodes.Circle010.geometry}
						material={materials.crema}
					/>
					<mesh
						name="Circle010_1"
						geometry={nodes.Circle010_1.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Circle010_2"
						geometry={nodes.Circle010_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane001"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane017_1"
						geometry={nodes.Plane017_1.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane017_2"
						geometry={nodes.Plane017_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane041"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane012_1"
						geometry={nodes.Plane012_1.geometry}
						material={materials.treeIsla5Tex}
					/>
					<mesh
						name="Plane012_2"
						geometry={nodes.Plane012_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Circle004"
					position={[272.705, 271.052, 0.999]}
					rotation={[0, 1.356, 0]}
					scale={0.332}
				>
					<mesh
						name="Circle011"
						geometry={nodes.Circle011.geometry}
						material={materials.alfombraIsla5Mat}
					/>
					<mesh
						name="Circle011_1"
						geometry={nodes.Circle011_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane012"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane089"
						geometry={nodes.Plane089.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane089_1"
						geometry={nodes.Plane089_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane016"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane090"
						geometry={nodes.Plane090.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane090_1"
						geometry={nodes.Plane090_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane017"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane091"
						geometry={nodes.Plane091.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane091_1"
						geometry={nodes.Plane091_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane018"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane092"
						geometry={nodes.Plane092.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane092_1"
						geometry={nodes.Plane092_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane019"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane093"
						geometry={nodes.Plane093.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane093_1"
						geometry={nodes.Plane093_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane021"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane094"
						geometry={nodes.Plane094.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane094_1"
						geometry={nodes.Plane094_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<mesh
					name="Circle005"
					geometry={nodes.Circle005.geometry}
					material={materials.maderaIsla5}
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				/>
				<group
					name="Plane006"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane013_1"
						geometry={nodes.Plane013_1.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane013_2"
						geometry={nodes.Plane013_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane007"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane014_1"
						geometry={nodes.Plane014_1.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane014_2"
						geometry={nodes.Plane014_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane013"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane015_1"
						geometry={nodes.Plane015_1.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane015_2"
						geometry={nodes.Plane015_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group name="Plane005" position={[273.977, 271.818, -2]} scale={0.439}>
					<mesh
						name="Plane019_1"
						geometry={nodes.Plane019_1.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane019_2"
						geometry={nodes.Plane019_2.geometry}
						material={materials["crema.001"]}
					/>
					<mesh
						name="Plane019_3"
						geometry={nodes.Plane019_3.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane010"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane024_1"
						geometry={nodes.Plane024_1.geometry}
						material={materials.techoIsla5}
					/>
					<mesh
						name="Plane024_2"
						geometry={nodes.Plane024_2.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane024_3"
						geometry={nodes.Plane024_3.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane008"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane026_1"
						geometry={nodes.Plane026_1.geometry}
						material={materials.clothIsla5Mat}
					/>
					<mesh
						name="Plane026_2"
						geometry={nodes.Plane026_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<mesh
					name="Plane004"
					geometry={nodes.Plane004.geometry}
					material={materials.treeIsla5Tex}
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				/>
				<mesh
					name="Plane015"
					geometry={nodes.Plane015.geometry}
					material={materials.treeIsla5Tex}
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				/>
				<mesh
					name="Circle006"
					geometry={nodes.Circle006.geometry}
					material={materials.grassIsla5Tex}
					position={[272.705, 270.551, 0.437]}
					rotation={[Math.PI, -1.286, Math.PI]}
					scale={0.473}
				/>
				<mesh
					name="planetaIsla5"
					geometry={nodes.planetaIsla5.geometry}
					material={materials.planetaIsla5Mat}
					position={[272.705, 270.551, 0.437]}
					scale={24.167}
				/>
				<mesh
					name="Plane020"
					geometry={nodes.Plane020.geometry}
					material={materials.CristalLight}
					position={[272.691, 272.925, 1.239]}
					rotation={[1.876, -0.31, -2.311]}
					scale={0.392}
				/>
				<mesh
					name="Plane024"
					geometry={nodes.Plane024.geometry}
					material={materials.CristalLight}
					position={[272.782, 272.851, 1.337]}
					rotation={[-1.186, 0.299, -0.922]}
					scale={0.392}
				/>
				<mesh
					name="Plane025"
					geometry={nodes.Plane025.geometry}
					material={materials.CristalLight}
					position={[272.771, 272.867, 1.273]}
					rotation={[0.835, 0.181, -1.109]}
					scale={0.392}
				/>
				<mesh
					name="Plane026"
					geometry={nodes.Plane026.geometry}
					material={materials.CristalLight}
					position={[272.722, 272.858, 1.421]}
					rotation={[-1.132, -0.207, -1.962]}
					scale={0.392}
				/>
				<mesh
					name="Plane027"
					geometry={nodes.Plane027.geometry}
					material={materials.CristalLight}
					position={[272.8, 272.892, 1.283]}
					rotation={[1.794, 0.829, -0.356]}
					scale={[0.328, 0.391, 0.392]}
				/>
				<mesh
					name="Plane028"
					geometry={nodes.Plane028.geometry}
					material={materials.CristalLight}
					position={[272.673, 272.884, 1.293]}
					rotation={[-1.563, -0.029, -3.105]}
					scale={[0.327, 0.392, 0.392]}
				/>
				<mesh
					name="Plane029"
					geometry={nodes.Plane029.geometry}
					material={materials.CristalLight}
					position={[272.782, 272.851, 1.337]}
					rotation={[-2.049, -0.068, 1.722]}
					scale={0.392}
				/>
				<mesh
					name="Plane011"
					geometry={nodes.Plane011.geometry}
					material={materials.CristalLight}
					position={[272.706, 272.851, 1.313]}
					rotation={[-1.132, -0.232, -1.886]}
					scale={0.392}
				/>
				<mesh
					name="Plane014"
					geometry={nodes.Plane014.geometry}
					material={materials.CristalLight}
					position={[272.706, 272.851, 1.347]}
					rotation={[-2.02, -0.293, -1.05]}
					scale={0.392}
				/>
				<mesh
					name="hojasIsla5"
					geometry={nodes.hojasIsla5.geometry}
					material={materials.treeIsla5Mat}
					position={[272.788, 276.441, 1.083]}
					rotation={[0.955, -0.015, -1.645]}
					scale={0.992}
				/>
				<group
					name="Plane022"
					position={[272.705, 270.551, 0.437]}
					scale={0.439}
				>
					<mesh
						name="Plane063"
						geometry={nodes.Plane063.geometry}
						material={materials["crema.001"]}
					/>
					<mesh
						name="Plane063_1"
						geometry={nodes.Plane063_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="Plane023"
					position={[271.38, 271.818, -2]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={0.439}
				>
					<mesh
						name="Plane064"
						geometry={nodes.Plane064.geometry}
						material={materials.maderaIsla5}
					/>
					<mesh
						name="Plane064_1"
						geometry={nodes.Plane064_1.geometry}
						material={materials["crema.001"]}
					/>
					<mesh
						name="Plane064_2"
						geometry={nodes.Plane064_2.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<mesh
					name="acceorios002"
					geometry={nodes.acceorios002.geometry}
					material={materials["character.001"]}
					position={[272.977, 271.657, 0.383]}
					rotation={[-1.428, -0.065, -0.425]}
					scale={1.015}
				/>
				<group
					name="fullBody002"
					position={[272.343, 271.454, 1.768]}
					rotation={[-0.048, -0.43, -0.02]}
					scale={1.015}
				>
					<mesh
						name="Face_(merged)(Clone)baked005"
						geometry={nodes["Face_(merged)(Clone)baked005"].geometry}
						material={materials["character.001"]}
					/>
					<mesh
						name="Face_(merged)(Clone)baked005_1"
						geometry={nodes["Face_(merged)(Clone)baked005_1"].geometry}
						material={materials.outlineMat}
					/>
				</group>
				<mesh
					name="pantaloneta"
					geometry={nodes.pantaloneta.geometry}
					material={materials.pantaloneta}
					position={[272.343, 271.454, 1.768]}
					rotation={[-0.048, -0.43, -0.02]}
					scale={1.015}
				/>
				<group
					name="camiseta"
					position={[272.343, 271.454, 1.768]}
					rotation={[-0.048, -0.43, -0.02]}
					scale={1.015}
				>
					<mesh
						name="Face_(merged)(Clone)baked010"
						geometry={nodes["Face_(merged)(Clone)baked010"].geometry}
						material={materials.camiseta}
					/>
					<mesh
						name="Face_(merged)(Clone)baked010_1"
						geometry={nodes["Face_(merged)(Clone)baked010_1"].geometry}
						material={materials.outlineMat}
					/>
				</group>
				<mesh
					name="acceorios003"
					geometry={nodes.acceorios003.geometry}
					material={materials["character.002"]}
					position={[272.705, 272.039, 4.246]}
					rotation={[-1.698, 0, 0]}
					scale={0.439}
				/>
				<group
					name="hair002"
					position={[273.024, 271.616, 0.268]}
					rotation={[-0.3, -0.021, -0.038]}
					scale={0.425}
				>
					<mesh
						name="RetopoFlow004"
						geometry={nodes.RetopoFlow004.geometry}
						material={materials["character.001"]}
					/>
					<mesh
						name="RetopoFlow004_1"
						geometry={nodes.RetopoFlow004_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="stalactiteIsla5"
					position={[272.832, 266.689, 0.483]}
					rotation={[-Math.PI, 1.292, -Math.PI]}
					scale={0.439}
				>
					<mesh
						name="Circle014"
						geometry={nodes.Circle014.geometry}
						material={materials.stalactitesIsla5Mat}
					/>
					<mesh
						name="Circle014_1"
						geometry={nodes.Circle014_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group
					name="crystalsIsla5"
					position={[272.729, 269.006, 4.003]}
					rotation={[0.857, -1.03, 0.112]}
					scale={0.439}
				>
					<mesh
						name="Cube003"
						geometry={nodes.Cube003.geometry}
						material={materials.treeIsla5Tex}
					/>
					<mesh
						name="Cube003_1"
						geometry={nodes.Cube003_1.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<mesh
					name="foliageIsla5"
					geometry={nodes.foliageIsla5.geometry}
					material={materials["foliageIsla2.001"]}
					position={[270.057, 270.524, -1.343]}
					rotation={[0, 0.92, 0]}
					scale={1.471}
				/>
				<group
					name="Circle007"
					position={[272.703, 273.023, 1.319]}
					scale={0.439}
				>
					<mesh
						name="Circle015_1"
						geometry={nodes.Circle015_1.geometry}
						material={materials["crema.001"]}
					/>
					<mesh
						name="Circle015_2"
						geometry={nodes.Circle015_2.geometry}
						material={materials.crystalIsla5Mat}
					/>
					<mesh
						name="Circle015_3"
						geometry={nodes.Circle015_3.geometry}
						material={materials.outlinewhiteIsla5}
					/>
					<mesh
						name="Circle015_4"
						geometry={nodes.Circle015_4.geometry}
						material={materials.outlineMat}
					/>
				</group>
				<group name="boxIsla6" rotation={[0, -0.05, 0]}>
					<mesh
						name="Circle017"
						geometry={nodes.Circle017.geometry}
						material={materials.boxIsla6Mat}
					/>
					<mesh
						name="Circle017_1"
						geometry={nodes.Circle017_1.geometry}
						material={materials.goldIsla6Mat}
					/>
					<mesh
						name="Circle017_2"
						geometry={nodes.Circle017_2.geometry}
						material={materials.boxIsla6Mat2}
					/>
					<mesh
						name="Circle017_3"
						geometry={nodes.Circle017_3.geometry}
						material={materials["outline.002"]}
					/>
				</group>
				<mesh
					name="planetIsla6"
					geometry={nodes.planetIsla6.geometry}
					material={materials.planetIsla6Mat}
					position={[368.536, 154.496, 0]}
					scale={24.847}
				/>
				<group
					name="detailsIsla6"
					position={[368.536, 154.496, 0]}
					scale={1.277}
				>
					<mesh
						name="Plane066_1"
						geometry={nodes.Plane066_1.geometry}
						material={materials.paisaje1Isla6Mat}
					/>
					<mesh
						name="Plane066_2"
						geometry={nodes.Plane066_2.geometry}
						material={materials.mouth}
					/>
					<mesh
						name="Plane066_3"
						geometry={nodes.Plane066_3.geometry}
						material={materials.maderaIsla6Mat}
					/>
					<mesh
						name="Plane066_4"
						geometry={nodes.Plane066_4.geometry}
						material={materials.paisaje2Isla6Mat}
					/>
					<mesh
						name="Plane066_5"
						geometry={nodes.Plane066_5.geometry}
						material={materials.goldIsla6Mat}
					/>
					<mesh
						name="Plane066_6"
						geometry={nodes.Plane066_6.geometry}
						material={materials.Paisaje3Isla6Mat}
					/>
					<mesh
						name="Plane066_7"
						geometry={nodes.Plane066_7.geometry}
						material={materials.Paisaje4Isla6Mat}
					/>
					<mesh
						name="Plane066_8"
						geometry={nodes.Plane066_8.geometry}
						material={materials.Paisaje5Isla6Mat}
					/>
					<mesh
						name="Plane066_9"
						geometry={nodes.Plane066_9.geometry}
						material={materials["outline.002"]}
					/>
					<group name="charactersIsla6" position={[-288.551, -120.965, 0]}>
						<mesh
							name="Face_(merged)(Clone)baked018"
							geometry={nodes["Face_(merged)(Clone)baked018"].geometry}
							material={materials["character.003"]}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_1"
							geometry={nodes["Face_(merged)(Clone)baked018_1"].geometry}
							material={materials.camisapaisaje4Isla6}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_2"
							geometry={nodes["Face_(merged)(Clone)baked018_2"].geometry}
							material={materials.camisapaisaje3Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_3"
							geometry={nodes["Face_(merged)(Clone)baked018_3"].geometry}
							material={materials.clothesPaisaje5Isla6}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_4"
							geometry={nodes["Face_(merged)(Clone)baked018_4"].geometry}
							material={materials.camisetaIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_5"
							geometry={nodes["Face_(merged)(Clone)baked018_5"].geometry}
							material={materials.pantsIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_6"
							geometry={nodes["Face_(merged)(Clone)baked018_6"].geometry}
							material={materials.maderaIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_7"
							geometry={nodes["Face_(merged)(Clone)baked018_7"].geometry}
							material={materials.camiseta2Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_8"
							geometry={nodes["Face_(merged)(Clone)baked018_8"].geometry}
							material={materials.mouth}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_9"
							geometry={nodes["Face_(merged)(Clone)baked018_9"].geometry}
							material={materials.pants2Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_10"
							geometry={nodes["Face_(merged)(Clone)baked018_10"].geometry}
							material={materials.Paisaje4Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked018_11"
							geometry={nodes["Face_(merged)(Clone)baked018_11"].geometry}
							material={materials["outline.002"]}
						/>
						<group name="accIsla6" position={[288.551, 120.965, 0]}>
							<mesh
								name="RetopoFlow015"
								geometry={nodes.RetopoFlow015.geometry}
								material={materials["character.003"]}
							/>
							<mesh
								name="RetopoFlow015_1"
								geometry={nodes.RetopoFlow015_1.geometry}
								material={materials["outline.002"]}
							/>
							<mesh
								name="RetopoFlow015_2"
								geometry={nodes.RetopoFlow015_2.geometry}
								material={materials.Paisaje3Isla6Mat}
							/>
							<mesh
								name="RetopoFlow015_3"
								geometry={nodes.RetopoFlow015_3.geometry}
								material={materials.dogmat}
							/>
							<mesh
								name="RetopoFlow015_4"
								geometry={nodes.RetopoFlow015_4.geometry}
								material={materials.Paisaje4Isla6Mat}
							/>
						</group>
					</group>
				</group>
				<group name="baseIsla7" position={[0, 0, -0.251]} scale={0.86}>
					<mesh
						name="Circle018"
						geometry={nodes.Circle018.geometry}
						material={materials.Cemento}
					/>
					<mesh
						name="Circle018_1"
						geometry={nodes.Circle018_1.geometry}
						material={materials.Teja2}
					/>
					<mesh
						name="Circle018_2"
						geometry={nodes.Circle018_2.geometry}
						material={materials.Teja}
					/>
					<mesh
						name="Circle018_3"
						geometry={nodes.Circle018_3.geometry}
						material={materials.accesorios}
					/>
					<mesh
						name="Circle018_4"
						geometry={nodes.Circle018_4.geometry}
						material={materials["outline.003"]}
					/>
				</group>
				<group
					name="casaIsla7"
					position={[446.032, 10.201, -0.238]}
					scale={0.435}
				>
					<mesh
						name="Plane067"
						geometry={nodes.Plane067.geometry}
						material={materials.maderaIsla7}
					/>
					<mesh
						name="Plane067_1"
						geometry={nodes.Plane067_1.geometry}
						material={materials.accesorios}
					/>
					<mesh
						name="Plane067_2"
						geometry={nodes.Plane067_2.geometry}
						material={materials.techoIsla7}
					/>
					<mesh
						name="Plane067_3"
						geometry={nodes.Plane067_3.geometry}
						material={materials.Cemento}
					/>
					<mesh
						name="Plane067_4"
						geometry={nodes.Plane067_4.geometry}
						material={materials["outline.003"]}
					/>
				</group>
				<group
					name="ventanaIsla7"
					position={[446.032, 10.201, -0.238]}
					scale={0.435}
				>
					<mesh
						name="Circle019"
						geometry={nodes.Circle019.geometry}
						material={materials.maderaIsla7}
					/>
					<mesh
						name="Circle019_1"
						geometry={nodes.Circle019_1.geometry}
						material={materials.accesorios}
					/>
					<mesh
						name="Circle019_2"
						geometry={nodes.Circle019_2.geometry}
						material={materials.paisaje}
					/>
				</group>
				<mesh
					name="planetIsla7"
					geometry={nodes.planetIsla7.geometry}
					material={materials.planetIsla7}
					position={[446.032, 10.286, -0.238]}
					rotation={[-Math.PI, 0.775, -Math.PI]}
					scale={-22.424}
				/>
				<mesh
					name="hairCharIsla7"
					geometry={nodes.hairCharIsla7.geometry}
					material={materials["character.004"]}
					position={[446.032, 11.36, 0.041]}
					scale={0.533}
				/>
				<group
					name="characterIsla7"
					position={[446.032, 10.932, 0.006]}
					scale={0.533}
				>
					<mesh
						name="Circle020"
						geometry={nodes.Circle020.geometry}
						material={materials.camisaIsla7Mat}
					/>
					<mesh
						name="Circle020_1"
						geometry={nodes.Circle020_1.geometry}
						material={materials["character.004"]}
					/>
					<mesh
						name="Circle020_2"
						geometry={nodes.Circle020_2.geometry}
						material={materials["outline.003"]}
					/>
				</group>
				<group
					name="acceoriesIsla7"
					position={[446.032, 10.26, -0.238]}
					scale={0.435}
				>
					<mesh
						name="Circle024"
						geometry={nodes.Circle024.geometry}
						material={materials.accesorios}
					/>
					<mesh
						name="Circle024_1"
						geometry={nodes.Circle024_1.geometry}
						material={materials["outline.003"]}
					/>
				</group>
				<group
					name="foliagesla7"
					position={[447.751, 13.133, -2.301]}
					rotation={[2.025, 0.431, 2.182]}
					scale={0.385}
				>
					<mesh
						name="Plane068_1"
						geometry={nodes.Plane068_1.geometry}
						material={materials["treeIsla5Mat.001"]}
					/>
					<mesh
						name="Plane068_2"
						geometry={nodes.Plane068_2.geometry}
						material={materials["foliageIsla2.002"]}
					/>
				</group>
				<group
					name="troncosIsla7"
					position={[446.032, 10.286, -0.238]}
					scale={0.435}
				>
					<mesh
						name="Plane069"
						geometry={nodes.Plane069.geometry}
						material={materials["treeIsla5Tex.001"]}
					/>
					<mesh
						name="Plane069_1"
						geometry={nodes.Plane069_1.geometry}
						material={materials["outline.003"]}
					/>
				</group>
				<mesh
					name="acceorios004"
					geometry={nodes.acceorios004.geometry}
					material={materials["character.005"]}
					position={[348.362, -153.288, -0.075]}
					rotation={[-Math.PI / 2, -0.218, -Math.PI / 2]}
					scale={[0.761, 0.998, 0.998]}
				/>
				<mesh
					name="fullBody003"
					geometry={nodes.fullBody003.geometry}
					material={materials["Material.002"]}
					position={[372.552, -156.055, -0.006]}
					scale={0.974}
				/>
				<mesh
					name="hair003"
					geometry={nodes.hair003.geometry}
					material={materials.maderaoscuraIsla8Mat}
					position={[372.552, -156.055, -0.006]}
					scale={0.974}
				/>
				<mesh
					name="camiseta001"
					geometry={nodes.camiseta001.geometry}
					material={materials["accesorios.001"]}
					position={[372.552, -156.055, -0.006]}
					scale={0.974}
				/>
				<group
					name="Plane035"
					position={[372.552, -156.055, -0.006]}
					scale={0.974}
				>
					<mesh
						name="Plane070_1"
						geometry={nodes.Plane070_1.geometry}
						material={materials.maderaoscuraIsla8Mat}
					/>
					<mesh
						name="Plane070_2"
						geometry={nodes.Plane070_2.geometry}
						material={materials["maderaIsla7.001"]}
					/>
					<mesh
						name="Plane070_3"
						geometry={nodes.Plane070_3.geometry}
						material={materials["accesorios.001"]}
					/>
					<mesh
						name="Plane070_4"
						geometry={nodes.Plane070_4.geometry}
						material={materials.black}
					/>
					<mesh
						name="Plane070_5"
						geometry={nodes.Plane070_5.geometry}
						material={materials["outline.004"]}
					/>
				</group>
				<group
					name="ventanaIsla7001"
					position={[371.227, -152.24, 0.059]}
					rotation={[0, 1.571, 0]}
					scale={[1.029, 1.029, 3.093]}
				>
					<mesh
						name="Circle021_1"
						geometry={nodes.Circle021_1.geometry}
						material={materials["maderaIsla7.001"]}
					/>
					<mesh
						name="Circle021_2"
						geometry={nodes.Circle021_2.geometry}
						material={materials.maderaoscuraIsla8Mat}
					/>
				</group>
				<mesh
					name="planetaIsla8"
					geometry={nodes.planetaIsla8.geometry}
					material={materials["Material.003"]}
					position={[372.113, -158.53, 0.036]}
					scale={-28.528}
				/>
				<group
					name="fullBody004"
					position={[376.229, -150.561, 0.031]}
					rotation={[-Math.PI, 1.176, -Math.PI]}
					scale={1.722}
				>
					<mesh
						name="Face_(merged)(Clone)baked008"
						geometry={nodes["Face_(merged)(Clone)baked008"].geometry}
						material={materials.outline2}
					/>
					<mesh
						name="Face_(merged)(Clone)baked008_1"
						geometry={nodes["Face_(merged)(Clone)baked008_1"].geometry}
						material={materials.OutlinePrueba}
					/>
				</group>
				<mesh
					name="acceorios005"
					geometry={nodes.acceorios005.geometry}
					material={materials.OutlinePrueba}
					position={[376.184, -150.056, 0.136]}
					rotation={[-Math.PI, 1.176, -Math.PI]}
					scale={1.722}
				/>
				<mesh
					name="Plane036"
					geometry={nodes.Plane036.geometry}
					material={materials["Material.006"]}
					position={[373.393, -153.096, -7.23]}
					rotation={[0.002, 0.17, 0.009]}
					scale={0.974}
				/>
				<group
					name="Sphere003"
					position={[376.14, -153.249, -0.006]}
					scale={0.442}
				>
					<mesh
						name="Sphere008"
						geometry={nodes.Sphere008.geometry}
						material={materials.outline2}
					/>
					<mesh
						name="Sphere008_1"
						geometry={nodes.Sphere008_1.geometry}
						material={materials.OutlinePrueba}
					/>
				</group>
				<mesh
					name="Sphere004"
					geometry={nodes.Sphere004.geometry}
					material={materials.OutlinePrueba}
					position={[376.084, -151.56, -0.006]}
					scale={2.349}
				/>
				<mesh
					name="Sphere005"
					geometry={nodes.Sphere005.geometry}
					material={materials.dreamIsla8Tex}
					position={[376.084, -151.56, -0.006]}
					scale={2.293}
				/>
				<mesh
					name="Plane037"
					geometry={nodes.Plane037.geometry}
					material={materials.wallIsla8Tex}
					position={[372.58, -156.122, -0.007]}
					scale={[1.029, 1.029, 1.081]}
				/>
				<mesh
					name="Sphere006"
					geometry={nodes.Sphere006.geometry}
					material={materials["Material.006"]}
					position={[376.084, -151.56, -0.006]}
					scale={2.767}
				/>
				<group
					name="Plane038"
					position={[372.552, -156.055, -0.006]}
					scale={0.974}
				>
					<mesh
						name="Plane077"
						geometry={nodes.Plane077.geometry}
						material={materials.crystalIsla8Mat}
					/>
					<mesh
						name="Plane077_1"
						geometry={nodes.Plane077_1.geometry}
						material={materials["outline.004"]}
					/>
				</group>
				<group
					name="Plane039"
					position={[372.552, -156.055, -0.006]}
					scale={0.974}
				>
					<mesh
						name="Plane078"
						geometry={nodes.Plane078.geometry}
						material={materials.maderaoscuraIsla8Mat}
					/>
					<mesh
						name="Plane078_1"
						geometry={nodes.Plane078_1.geometry}
						material={materials["accesorios.001"]}
					/>
					<mesh
						name="Plane078_2"
						geometry={nodes.Plane078_2.geometry}
						material={materials["Material.005"]}
					/>
					<mesh
						name="Plane078_3"
						geometry={nodes.Plane078_3.geometry}
						material={materials.cuadrro1}
					/>
					<mesh
						name="Plane078_4"
						geometry={nodes.Plane078_4.geometry}
						material={materials.cuadro2}
					/>
					<mesh
						name="Plane078_5"
						geometry={nodes.Plane078_5.geometry}
						material={materials.bedIsla8Mat}
					/>
					<mesh
						name="Plane078_6"
						geometry={nodes.Plane078_6.geometry}
						material={materials.wallIsla8Tex}
					/>
					<mesh
						name="Plane078_7"
						geometry={nodes.Plane078_7.geometry}
						material={materials["outline.004"]}
					/>
				</group>
				<group
					name="Plane040"
					position={[372.552, -156.055, -0.006]}
					scale={0.974}
				>
					<mesh
						name="Plane079"
						geometry={nodes.Plane079.geometry}
						material={materials["grass.001"]}
					/>
					<mesh
						name="Plane079_1"
						geometry={nodes.Plane079_1.geometry}
						material={materials["outline.004"]}
					/>
				</group>
				<group
					name="Plane042"
					position={[372.552, -156.055, -0.006]}
					scale={0.974}
				>
					<mesh
						name="Plane080"
						geometry={nodes.Plane080.geometry}
						material={materials.crystalIsla8Mat2}
					/>
					<mesh
						name="Plane080_1"
						geometry={nodes.Plane080_1.geometry}
						material={materials["outline.004"]}
					/>
				</group>
				<group
					name="nube7"
					position={[217.268, -256.422, 0.143]}
					rotation={[0.081, 0.02, 0.003]}
					scale={0.793}
				>
					<mesh
						name="nube7_1"
						geometry={nodes.nube7_1.geometry}
						material={materials.nube7}
					/>
					<mesh
						name="nube7_2"
						geometry={nodes.nube7_2.geometry}
						material={materials.Outline2}
					/>
				</group>
				<mesh
					name="nube7001"
					geometry={nodes.nube7001.geometry}
					material={materials.stars}
					position={[217.268, -256.422, 0.143]}
					rotation={[0.081, 0.02, 0.003]}
					scale={0.874}
				/>
				<mesh
					name="nube7002"
					geometry={nodes.nube7002.geometry}
					material={materials.stars}
					position={[217.268, -256.422, 0.143]}
					rotation={[0.081, 0.02, 0.003]}
					scale={1.038}
				/>
				<group
					name="dragonIlsa9Head"
					position={[217.369, -253.645, 1.788]}
					scale={0.793}
				>
					<mesh
						name="RetopoFlow006"
						geometry={nodes.RetopoFlow006.geometry}
						material={materials.dragonHeadIsla9Mat}
					/>
					<mesh
						name="RetopoFlow006_1"
						geometry={nodes.RetopoFlow006_1.geometry}
						material={materials["accesorios.002"]}
					/>
					<mesh
						name="RetopoFlow006_2"
						geometry={nodes.RetopoFlow006_2.geometry}
						material={materials.Outline}
					/>
				</group>
				<mesh
					name="planetIsla9"
					geometry={nodes.planetIsla9.geometry}
					material={materials.planetaIsla9Mat}
					position={[217.268, -256.422, 0.143]}
					scale={-28.919}
				/>
				<group
					name="dragonIsla9Acc"
					position={[217.369, -253.645, 1.788]}
					scale={0.793}
				>
					<mesh
						name="RetopoFlow009"
						geometry={nodes.RetopoFlow009.geometry}
						material={materials["accesorios.002"]}
					/>
					<mesh
						name="RetopoFlow009_1"
						geometry={nodes.RetopoFlow009_1.geometry}
						material={materials.Outline}
					/>
				</group>
				<group
					name="dragonIlsa9Cuerpo"
					position={[217.369, -254.733, 1.788]}
					scale={0.793}
				>
					<mesh
						name="Plane081"
						geometry={nodes.Plane081.geometry}
						material={materials.dragonBodyIsla6Mat}
					/>
					<mesh
						name="Plane081_1"
						geometry={nodes.Plane081_1.geometry}
						material={materials.Outline}
					/>
				</group>
				<group
					name="baseIsla9"
					position={[217.268, -254.488, 0.143]}
					scale={[0.793, 1.405, 0.793]}
				>
					<mesh
						name="Circle023"
						geometry={nodes.Circle023.geometry}
						material={materials.baseIsla9}
					/>
					<mesh
						name="Circle023_1"
						geometry={nodes.Circle023_1.geometry}
						material={materials.Outline3}
					/>
				</group>
				<group
					name="dragonIsla9Legs_Low"
					position={[217.268, -256.422, 0.143]}
					scale={0.793}
				>
					<mesh
						name="Plane087"
						geometry={nodes.Plane087.geometry}
						material={materials.dragonIsla9LegsMat}
					/>
					<mesh
						name="Plane087_1"
						geometry={nodes.Plane087_1.geometry}
						material={materials.Outline}
					/>
				</group>
				<group name="boxIsla6001" rotation={[0, -0.05, 0]}>
					<mesh
						name="Circle025"
						geometry={nodes.Circle025.geometry}
						material={materials.boxIsla6Mat}
					/>
					<mesh
						name="Circle025_1"
						geometry={nodes.Circle025_1.geometry}
						material={materials.goldIsla6Mat}
					/>
					<mesh
						name="Circle025_2"
						geometry={nodes.Circle025_2.geometry}
						material={materials.boxIsla6Mat2}
					/>
					<mesh
						name="Circle025_3"
						geometry={nodes.Circle025_3.geometry}
						material={materials["outline.002"]}
					/>
				</group>
				<mesh
					name="planetaIsla10"
					geometry={nodes.planetaIsla10.geometry}
					material={materials.planetIsla6Mat}
					position={[44.55, -336.309, 0]}
					scale={24.847}
				/>
				<group
					name="detailsIsla6001"
					position={[44.55, -336.309, 0]}
					scale={1.277}
				>
					<mesh
						name="Plane088"
						geometry={nodes.Plane088.geometry}
						material={materials.paisaje1Isla6Mat}
					/>
					<mesh
						name="Plane088_1"
						geometry={nodes.Plane088_1.geometry}
						material={materials.mouth}
					/>
					<mesh
						name="Plane088_2"
						geometry={nodes.Plane088_2.geometry}
						material={materials.maderaIsla6Mat}
					/>
					<mesh
						name="Plane088_3"
						geometry={nodes.Plane088_3.geometry}
						material={materials.paisaje2Isla6Mat}
					/>
					<mesh
						name="Plane088_4"
						geometry={nodes.Plane088_4.geometry}
						material={materials.goldIsla6Mat}
					/>
					<mesh
						name="Plane088_5"
						geometry={nodes.Plane088_5.geometry}
						material={materials.Paisaje3Isla6Mat}
					/>
					<mesh
						name="Plane088_6"
						geometry={nodes.Plane088_6.geometry}
						material={materials.Paisaje4Isla6Mat}
					/>
					<mesh
						name="Plane088_7"
						geometry={nodes.Plane088_7.geometry}
						material={materials.Paisaje5Isla6Mat}
					/>
					<mesh
						name="Plane088_8"
						geometry={nodes.Plane088_8.geometry}
						material={materials["outline.002"]}
					/>
					<group name="charactersIsla6001" position={[-34.881, 263.318, 0]}>
						<mesh
							name="Face_(merged)(Clone)baked009"
							geometry={nodes["Face_(merged)(Clone)baked009"].geometry}
							material={materials["character.003"]}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_1"
							geometry={nodes["Face_(merged)(Clone)baked009_1"].geometry}
							material={materials.camisapaisaje4Isla6}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_2"
							geometry={nodes["Face_(merged)(Clone)baked009_2"].geometry}
							material={materials.camisapaisaje3Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_3"
							geometry={nodes["Face_(merged)(Clone)baked009_3"].geometry}
							material={materials.clothesPaisaje5Isla6}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_4"
							geometry={nodes["Face_(merged)(Clone)baked009_4"].geometry}
							material={materials.camisetaIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_5"
							geometry={nodes["Face_(merged)(Clone)baked009_5"].geometry}
							material={materials.pantsIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_6"
							geometry={nodes["Face_(merged)(Clone)baked009_6"].geometry}
							material={materials.maderaIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_7"
							geometry={nodes["Face_(merged)(Clone)baked009_7"].geometry}
							material={materials.camiseta2Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_8"
							geometry={nodes["Face_(merged)(Clone)baked009_8"].geometry}
							material={materials.mouth}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_9"
							geometry={nodes["Face_(merged)(Clone)baked009_9"].geometry}
							material={materials.pants2Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_10"
							geometry={nodes["Face_(merged)(Clone)baked009_10"].geometry}
							material={materials.Paisaje4Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked009_11"
							geometry={nodes["Face_(merged)(Clone)baked009_11"].geometry}
							material={materials["outline.002"]}
						/>
						<group name="accIsla6001" position={[34.881, -263.318, 0]}>
							<mesh
								name="RetopoFlow008"
								geometry={nodes.RetopoFlow008.geometry}
								material={materials["character.003"]}
							/>
							<mesh
								name="RetopoFlow008_1"
								geometry={nodes.RetopoFlow008_1.geometry}
								material={materials["outline.002"]}
							/>
							<mesh
								name="RetopoFlow008_2"
								geometry={nodes.RetopoFlow008_2.geometry}
								material={materials.Paisaje3Isla6Mat}
							/>
							<mesh
								name="RetopoFlow008_3"
								geometry={nodes.RetopoFlow008_3.geometry}
								material={materials.dogmat}
							/>
							<mesh
								name="RetopoFlow008_4"
								geometry={nodes.RetopoFlow008_4.geometry}
								material={materials.Paisaje4Isla6Mat}
							/>
						</group>
					</group>
				</group>
				<group name="boxIsla6002" rotation={[0, -0.05, 0]}>
					<mesh
						name="Circle026"
						geometry={nodes.Circle026.geometry}
						material={materials.boxIsla6Mat}
					/>
					<mesh
						name="Circle026_1"
						geometry={nodes.Circle026_1.geometry}
						material={materials.goldIsla6Mat}
					/>
					<mesh
						name="Circle026_2"
						geometry={nodes.Circle026_2.geometry}
						material={materials.boxIsla6Mat2}
					/>
					<mesh
						name="Circle026_3"
						geometry={nodes.Circle026_3.geometry}
						material={materials["outline.002"]}
					/>
				</group>
				<mesh
					name="planetIsla11"
					geometry={nodes.planetIsla11.geometry}
					material={materials.planetIsla6Mat}
					position={[-116.753, -303.221, 0]}
					scale={24.847}
				/>
				<group
					name="detailsIsla6002"
					position={[-116.753, -303.221, 0]}
					scale={1.277}
				>
					<mesh
						name="Plane095"
						geometry={nodes.Plane095.geometry}
						material={materials.paisaje1Isla6Mat}
					/>
					<mesh
						name="Plane095_1"
						geometry={nodes.Plane095_1.geometry}
						material={materials.mouth}
					/>
					<mesh
						name="Plane095_2"
						geometry={nodes.Plane095_2.geometry}
						material={materials.maderaIsla6Mat}
					/>
					<mesh
						name="Plane095_3"
						geometry={nodes.Plane095_3.geometry}
						material={materials.paisaje2Isla6Mat}
					/>
					<mesh
						name="Plane095_4"
						geometry={nodes.Plane095_4.geometry}
						material={materials.goldIsla6Mat}
					/>
					<mesh
						name="Plane095_5"
						geometry={nodes.Plane095_5.geometry}
						material={materials.Paisaje3Isla6Mat}
					/>
					<mesh
						name="Plane095_6"
						geometry={nodes.Plane095_6.geometry}
						material={materials.Paisaje4Isla6Mat}
					/>
					<mesh
						name="Plane095_7"
						geometry={nodes.Plane095_7.geometry}
						material={materials.Paisaje5Isla6Mat}
					/>
					<mesh
						name="Plane095_8"
						geometry={nodes.Plane095_8.geometry}
						material={materials["outline.002"]}
					/>
					<group name="charactersIsla6002" position={[91.414, 237.412, 0]}>
						<mesh
							name="Face_(merged)(Clone)baked011"
							geometry={nodes["Face_(merged)(Clone)baked011"].geometry}
							material={materials["character.003"]}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_1"
							geometry={nodes["Face_(merged)(Clone)baked011_1"].geometry}
							material={materials.camisapaisaje4Isla6}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_2"
							geometry={nodes["Face_(merged)(Clone)baked011_2"].geometry}
							material={materials.camisapaisaje3Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_3"
							geometry={nodes["Face_(merged)(Clone)baked011_3"].geometry}
							material={materials.clothesPaisaje5Isla6}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_4"
							geometry={nodes["Face_(merged)(Clone)baked011_4"].geometry}
							material={materials.camisetaIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_5"
							geometry={nodes["Face_(merged)(Clone)baked011_5"].geometry}
							material={materials.pantsIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_6"
							geometry={nodes["Face_(merged)(Clone)baked011_6"].geometry}
							material={materials.maderaIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_7"
							geometry={nodes["Face_(merged)(Clone)baked011_7"].geometry}
							material={materials.camiseta2Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_8"
							geometry={nodes["Face_(merged)(Clone)baked011_8"].geometry}
							material={materials.mouth}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_9"
							geometry={nodes["Face_(merged)(Clone)baked011_9"].geometry}
							material={materials.pants2Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_10"
							geometry={nodes["Face_(merged)(Clone)baked011_10"].geometry}
							material={materials.Paisaje4Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked011_11"
							geometry={nodes["Face_(merged)(Clone)baked011_11"].geometry}
							material={materials["outline.002"]}
						/>
						<group name="accIsla6002" position={[-91.414, -237.412, 0]}>
							<mesh
								name="RetopoFlow010"
								geometry={nodes.RetopoFlow010.geometry}
								material={materials["character.003"]}
							/>
							<mesh
								name="RetopoFlow010_1"
								geometry={nodes.RetopoFlow010_1.geometry}
								material={materials["outline.002"]}
							/>
							<mesh
								name="RetopoFlow010_2"
								geometry={nodes.RetopoFlow010_2.geometry}
								material={materials.Paisaje3Isla6Mat}
							/>
							<mesh
								name="RetopoFlow010_3"
								geometry={nodes.RetopoFlow010_3.geometry}
								material={materials.dogmat}
							/>
							<mesh
								name="RetopoFlow010_4"
								geometry={nodes.RetopoFlow010_4.geometry}
								material={materials.Paisaje4Isla6Mat}
							/>
						</group>
					</group>
				</group>
				<group name="boxIsla6003" rotation={[0, -0.05, 0]}>
					<mesh
						name="Circle027"
						geometry={nodes.Circle027.geometry}
						material={materials.boxIsla6Mat}
					/>
					<mesh
						name="Circle027_1"
						geometry={nodes.Circle027_1.geometry}
						material={materials.goldIsla6Mat}
					/>
					<mesh
						name="Circle027_2"
						geometry={nodes.Circle027_2.geometry}
						material={materials.boxIsla6Mat2}
					/>
					<mesh
						name="Circle027_3"
						geometry={nodes.Circle027_3.geometry}
						material={materials["outline.002"]}
					/>
				</group>
				<mesh
					name="planetIsla12"
					geometry={nodes.planetIsla12.geometry}
					material={materials.planetIsla6Mat}
					position={[-253.241, -177.762, 0]}
					scale={24.847}
				/>
				<group
					name="detailsIsla6003"
					position={[-253.241, -177.762, 0]}
					scale={1.277}
				>
					<mesh
						name="Plane096"
						geometry={nodes.Plane096.geometry}
						material={materials.paisaje1Isla6Mat}
					/>
					<mesh
						name="Plane096_1"
						geometry={nodes.Plane096_1.geometry}
						material={materials.mouth}
					/>
					<mesh
						name="Plane096_2"
						geometry={nodes.Plane096_2.geometry}
						material={materials.maderaIsla6Mat}
					/>
					<mesh
						name="Plane096_3"
						geometry={nodes.Plane096_3.geometry}
						material={materials.paisaje2Isla6Mat}
					/>
					<mesh
						name="Plane096_4"
						geometry={nodes.Plane096_4.geometry}
						material={materials.goldIsla6Mat}
					/>
					<mesh
						name="Plane096_5"
						geometry={nodes.Plane096_5.geometry}
						material={materials.Paisaje3Isla6Mat}
					/>
					<mesh
						name="Plane096_6"
						geometry={nodes.Plane096_6.geometry}
						material={materials.Paisaje4Isla6Mat}
					/>
					<mesh
						name="Plane096_7"
						geometry={nodes.Plane096_7.geometry}
						material={materials.Paisaje5Isla6Mat}
					/>
					<mesh
						name="Plane096_8"
						geometry={nodes.Plane096_8.geometry}
						material={materials["outline.002"]}
					/>
					<group name="charactersIsla6003" position={[198.279, 139.182, 0]}>
						<mesh
							name="Face_(merged)(Clone)baked013"
							geometry={nodes["Face_(merged)(Clone)baked013"].geometry}
							material={materials["character.003"]}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_1"
							geometry={nodes["Face_(merged)(Clone)baked013_1"].geometry}
							material={materials.camisapaisaje4Isla6}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_2"
							geometry={nodes["Face_(merged)(Clone)baked013_2"].geometry}
							material={materials.camisapaisaje3Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_3"
							geometry={nodes["Face_(merged)(Clone)baked013_3"].geometry}
							material={materials.clothesPaisaje5Isla6}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_4"
							geometry={nodes["Face_(merged)(Clone)baked013_4"].geometry}
							material={materials.camisetaIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_5"
							geometry={nodes["Face_(merged)(Clone)baked013_5"].geometry}
							material={materials.pantsIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_6"
							geometry={nodes["Face_(merged)(Clone)baked013_6"].geometry}
							material={materials.maderaIsla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_7"
							geometry={nodes["Face_(merged)(Clone)baked013_7"].geometry}
							material={materials.camiseta2Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_8"
							geometry={nodes["Face_(merged)(Clone)baked013_8"].geometry}
							material={materials.mouth}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_9"
							geometry={nodes["Face_(merged)(Clone)baked013_9"].geometry}
							material={materials.pants2Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_10"
							geometry={nodes["Face_(merged)(Clone)baked013_10"].geometry}
							material={materials.Paisaje4Isla6Mat}
						/>
						<mesh
							name="Face_(merged)(Clone)baked013_11"
							geometry={nodes["Face_(merged)(Clone)baked013_11"].geometry}
							material={materials["outline.002"]}
						/>
						<group name="accIsla6003" position={[-198.279, -139.182, 0]}>
							<mesh
								name="RetopoFlow011"
								geometry={nodes.RetopoFlow011.geometry}
								material={materials["character.003"]}
							/>
							<mesh
								name="RetopoFlow011_1"
								geometry={nodes.RetopoFlow011_1.geometry}
								material={materials["outline.002"]}
							/>
							<mesh
								name="RetopoFlow011_2"
								geometry={nodes.RetopoFlow011_2.geometry}
								material={materials.Paisaje3Isla6Mat}
							/>
							<mesh
								name="RetopoFlow011_3"
								geometry={nodes.RetopoFlow011_3.geometry}
								material={materials.dogmat}
							/>
							<mesh
								name="RetopoFlow011_4"
								geometry={nodes.RetopoFlow011_4.geometry}
								material={materials.Paisaje4Isla6Mat}
							/>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/../src/assets/scene/EscenadePrueba1.gltf");
